name: Linux GCC

on: [pull_request]

#concurrency:
#  group: ${{ github.ref }}-${{ github.head_ref }}-linux-gcc
#  cancel-in-progress: true

jobs:
  library:
    name: GNU@9.3 C++17 Release
    runs-on: ubuntu-20.04
    # env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual"}
    steps:
    - name: checkout driver
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        cd ${{github.workspace}}
        git submodule update --init --depth=1
        ./Submodules/amrex/.github/workflows/dependencies/dependencies.sh

    - name: Run megabuild script
      run: |
        cd ${{github.workspace}}/..
        ./erf-amrwind-driver/Build/megabuild.sh

    - name: Run Couette flow problem
      run: |
        cd ${{github.workspace}}/../erf-amrwind-driver-install/bin
        cp ${{github.workspace}}/Exec/CouetteFlow/input* .
        ./erf_mb_couette inputs_amrex
